export type MenuItem = { name: string; note?: string; };
export type MenuSection = { title: string; subtitle?: string; items: MenuItem[]; };

export const menuSections: MenuSection[] = [
  {
    title: "Appetizers",
    items: [
      { name: "Hummus", note: "Add chicken or beef $2.00" },
      { name: "Baba Ganoush" },
      { name: "Falafel (6 pcs)" },
      { name: "Kibbeh (each)" },
      { name: "Spinach Dip" },
      { name: "Calamari" },
      { name: "Nachos", note: "Add chicken or beef $3.00" },
      { name: "Cheese Sticks (5 pcs)" },
      { name: "Honey Chilli Fries" },
      { name: "Coconut Shrimp" },
      { name: "Wings" },
    ],
  },
  {
    title: "Salads",
    items: [
      { name: "Tabbouleh" },
      { name: "Fattoush" },
      { name: "Garden Salad" },
      { name: "Greek Salad" },
      { name: "Mayjjana Salad" },
      { name: "Caesar Salad" },
    ],
  },
  {
    title: "Sides",
    items: [
      { name: "Fries" },
      { name: "Onion Rings" },
      { name: "Rice" },
      { name: "Roasted Veggies" },
      { name: "Poutine", note: "Add chicken or beef $3.00" },
      { name: "Tawook Skewer" },
      { name: "Kafta Skewer" },
      { name: "Shrimp Skewer" },
      { name: "Tandoori Skewer" },
    ],
  },
  {
    title: "Manakish",
    items: [
      { name: "Zaatar" },
      { name: "Zaatar With Cheese" },
      { name: "Cheese" },
      { name: "Cheese With Zaatar" },
      { name: "Beef" },
      { name: "Beef With Cheese" },
      { name: "Chicken With Cheese" },
      { name: "Salami Pizza" },
      { name: "Veggie Pizza" },
    ],
  },
  {
    title: "Mains",
    subtitle: "All served with 2 sides of your choice: rice, veggies, salad",
    items: [
      { name: "Tawook Plate" },
      { name: "Kafta Plate" },
      { name: "Chicken Tandoori" },
      { name: "Shrimp" },
      { name: "Salmon" },
      { name: "Penne Pasta" },
      { name: "Steak" },
      { name: "Chicken Mushroom" },
    ],
  },
  {
    title: "Burgers & Wraps",
    subtitle: "Served with fries. Add salad $3.50 | cheese $1.00",
    items: [
      { name: "Beef Burger" },
      { name: "Chicken Burger" },
      { name: "Veggie Burger" },
      { name: "Mayjjana Burger" },
      { name: "Chicken Fajita" },
      { name: "Philly Steak" },
      { name: "Arabic Chicken Wrap" },
      { name: "Pesto Chicken Wrap" },
      { name: "Chicken Tawook Pita Wrap" },
      { name: "Kafta Kabab Pita Wrap" },
      { name: "Fries Sandwich Pita Wrap" },
      { name: "Falafel Pita Wrap" },
    ],
  },
  {
    title: "Juices",
    items: [
      { name: "Orange" },
      { name: "Lemon Mint" },
      { name: "Mango" },
      { name: "Strawberry" },
      { name: "Strawberry Mango" },
      { name: "Fruit Cocktail" },
    ],
  },
  {
    title: "Shakes",
    items: [
      { name: "Strawberry Banana" },
      { name: "Banana" },
      { name: "Strawberry" },
      { name: "Avocado" },
      { name: "Avocado Banana" },
      { name: "Mango" },
      { name: "Chocolate Shake" },
    ],
  },
  {
    title: "Cold Beverages",
    items: [
      { name: "Red Bull" },
      { name: "Perrier" },
      { name: "Barbican" },
      { name: "Pop" },
      { name: "Water" },
    ],
  },
  {
    title: "Hot Beverages",
    items: [
      { name: "Tea Cup" },
      { name: "Tea Pot" },
      { name: "American Coffee" },
      { name: "Cappuccino" },
      { name: "Espresso (Single)" },
      { name: "Espresso (Double)" },
      { name: "Turkish Coffee (Single)" },
      { name: "Turkish Coffee (Double)" },
    ],
  },
  {
    title: "Desserts",
    items: [
      { name: "Chocolate Cake" },
      { name: "Cheese Cake" },
      { name: "Kanafa" },
      { name: "Arabic Ice Cream" },
      { name: "Chocolate Ice Cream" },
      { name: "Vanilla Ice Cream" },
      { name: "Strawberry Ice Cream" },
      { name: "Baklava" },
    ],
  },
  {
    title: "Shisha",
    subtitle: "Ask your server for availability. Lounge offerings are for adults only where required by law.",
    items: [
      { name: "Regular Head: Double Apple, Grape Mint, Peach, Mango, Watermelon, Lemon Mint, Mint, Gum Mint, Orange, Rose, Strawberry, Grape Berry, Grapefruit, Blueberry, Kiwi" },
      { name: "House Mix & Starbuzz: Mayjjana Mix, Queen Of Sex, Code 69, Bluemist, Sex On The Beach, Citrus Mist" },
      { name: "Special Heads: Pineapple, Pineapple With Starbuzz, Ice Shisha, Ice Pipe, Extra Head" },
      { name: "Orange Head Flavors: Double Apple, Grape, Grape Mint, Peach, Orange, Vanilla, Rose, Strawberry, Mango, Grape Berry, Watermelon, Grapefruit, Lemon Mint, Blue Berry, Mint, Kiwi, Gum Mint (All shisha comes with orange heads)" },
    ],
  },
];
